spring:
  datasource:
    url: jdbc:mysql://root@localhost:3306/cloud_vendor
    username: root
    password: Gaurav@7776

#jpa:
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA Settings
  jpa.hibernate.ddl_auto: create


